[tool.poetry]
name = "awslambda"
version = "0.1.0"
description = ""
authors = ["TJ <tbruno25@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
nba-api = "^1.4.1"
pandas = "^2.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
